jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 9000
   servlet:
      context-path: /adn-jefferson-rios
      session:
         timeout: 21600s

spring:
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/adnceiba
      username: root
      password: CSH*1097403694
      hikari:
         poolName: pool
